name: Deploy to Github Pages
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
     - name: 🧐 Checkout
       id: checkout
       uses: actions/checkout@v4

     - name: 🔧 Setup pnpm
       id: setup_pnpm
       uses: pnpm/action-setup@v4
       with:
         version: latest

     - name: 🚧 Setup dependencies
       id: setup_deps
       run: |
         pnpm install

     - name: 📦 Build production pages
       id: build
       run: |
         mv docs/.vitepress/config.ts docs/.vitepress/config.ts.bak
         mv docs/.vitepress/config.pages.ts docs/.vitepress/config.ts
         pnpm run build
         cp docs/assets/logo.png dist/assets/

     - name: 🚀 Deploy to Github Pages
       id: deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         folder: dist
         branch: gh-pages
         token: ${{ secrets.DEPLOY_TOKEN }}
